//created on: May 16, 2021
package rules

//list any import classes here.
import com.sbnz.helpers.Utility;
import com.sbnz.model.RegisteredUser;
import com.sbnz.model.Destination;
import com.sbnz.model.Category;
import com.sbnz.model.Hotel;
import com.sbnz.dto.SearchDTO;
import com.sbnz.model.LocalFood;
import com.sbnz.model.Transportation;


rule "Add points to destinations with distance smaller than user's max distance"
    agenda-group "distance"
    no-loop true
	lock-on-active true
    when
        $search: SearchDTO($maxDistance: maxDistance)  
        $destination: Destination($lat1: locationLat, $lon1: locationLon)
        $user: RegisteredUser($userLat: locationLat, $userLon: locationLon)
    
    	$distance: Double() from Utility.distance($lat1, $lon1, $userLat, $userLon)
    	eval($distance <= $maxDistance)
    then
		modify($destination) {
			setScore($destination.getScore() + 5);	
		}
	    System.out.println("10 points goes to "+$destination.getName()+" for fitting into user's maximum distance: "+$maxDistance);	
       
end